# Generated by Django 2.1.7 on 2019-02-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annuaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='inconnu', max_length=100)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('pw', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'ordering': ('-last_modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-last_modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Perimetre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('annuaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perimetres', to='perimetre.Annuaire')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perimetres', to='perimetre.Client')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perimetres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_modified', '-created'),
            },
        ),
    ]
